server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    load balancer:
      enabled: true
    gateway:
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/products/**,/api/category/**
          filters:
            - SetPath=/v3/api-docs

        - id: supplier
          uri: lb://SUPPLIER
          predicates:
            - Path=/api/suppliers/**
          filters:
            - SetPath=/v3/api-docs

        - id: purchase
          uri: lb://PURCHASE
          predicates:
            - Path=/api/purchases/**
          filters:
            - SetPath=/v3/api-docs


        - id: sales
          uri: lb://SALES
          predicates:
            - Path=/api/sales/**
          filters:
            - SetPath=/v3/api-docs

        - id: inventory
          uri: lb://INVENTORY
          predicates:
            - Path=/api/inventory/**
          filters:
            - SetPath=/v3/api-docs

        - id: REPORT
          uri: lb://REPORT
          predicates:
            - Path=/api/report/**
          filters:
            - SetPath=/v3/api-docs

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

    urls:
      - name: Product Service
        url: /api/products/v3/api-docs

      - name: Supplier Service
        url: /api/suppliers/v3/api-docs

      - name: Purchase Service
        url: /api/purchases/v3/api-docs

      - name: Sales Service
        url: /api/sales/v3/api-docs

      - name: Inventory Service
        url: /api/inventory/v3/api-docs

      - name: Report Service
        url: /api/report/v3/api-docs


