server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    load balancer:
      enabled: true
    gateway:
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/products/**,/api/category/**
        - id: supplier
          uri: lb://SUPPLIER
          predicates:
            - Path=/api/suppliers/**
        - id: purchase
          uri: lb://PURCHASE
          predicates:
            - Path=/api/purchases/**
        - id: sales
          uri: lb://SALES
          predicates:
            - Path=/api/sales/**
        - id: inventory
          uri: lb://INVENTORY
          predicates:
            - Path=/api/inventory/**